name: Update assets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: updater
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: tohenk/ntjs-web-assets
        token: ${{ secrets.TOKEN }}
        path: repository
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        cache-dependency-path: 'updater/package-lock.json'
    - name: Install dependencies
      run: cd updater && npm update
    - name: Update assets
      run: |
        cd updater
        if [ "x${_VERBOSE}" = "xTRUE" -o "x${_VERBOSE}" = "x1" ]; then
          node index.js --verbose ../repository
        else
          node index.js ../repository
        fi
      env:
        _VERBOSE: ${{ vars.UPDATE_VERBOSE }}
    - name: Commit assets changes
      run: |
        cd repository
        CD=$(pwd)

        set +e

        git config user.name github-actions
        git config user.email github-actions@github.com

        PKG=0
        [ "x${_EACH_PACKAGE}" = "xTRUE" -o "x${_EACH_PACKAGE}" = "x1" ] && PKG=1
        CNT=0
        CHANGES=""

        ### check changes of each package and commit if necessary
        for DIR in `ls`; do
          if [ -d "${CD}/${DIR}" ]; then
            cd "${CD}/${DIR}"
            CHANGED=$(git diff .)
            if [ -n "${CHANGED}" ]; then
              VER=$(awk "/\"${DIR}\": {/,/\"version\": \"*\"/ { if (\$2 != \"{\") print \$2 }" ${CD}/cdn.json | egrep -o "([0-9]{1,}\.)+[0-9]{1,}[A-Za-z0-9\-]{0,}")
              if [ -n "${VER}" ]; then
                MSG="Update ${DIR} to ${VER}"
              else
                MSG="Update ${DIR}"
              fi
              echo "> ${DIR} ${VER}"
              git add .
              if [ $PKG -eq 1 ]; then
                git commit -m "${MSG}."
              else
                if [ -n "${CHANGES}" ]; then
                  CHANGES+="
        "
                fi
                CHANGES+="- ${MSG}"
              fi
              CNT=$((CNT+1))
            fi
          fi
        done

        cd ${CD}

        ### check for cdn.json changes
        if [ -n "$(git diff cdn.json)" ]; then
          git add cdn.json
          if [ $PKG -eq 1 ]; then
            git commit -m "Automatic CDN update."
          fi
          CNT=$((CNT+1))
        fi

        ### commit changes and push commits
        if [ $CNT -gt 0 ]; then
          echo "Pushing changes..."
          if [ $PKG -eq 0 ]; then
            git commit -m "Automatic assets update.

        ${CHANGES}"
          fi
          git push
        fi
      env:
        _EACH_PACKAGE: ${{ vars.UPDATE_COMMIT_PACKAGE }}