name: Update assets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: updater
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: tohenk/ntjs-web-assets
        token: ${{ secrets.TOKEN }}
        path: repository
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        cache-dependency-path: 'updater/package-lock.json'
    - name: Install dependencies
      run: cd updater && npm update
    - name: Update assets
      run: |
        cd updater
        if [ "x${_VERBOSE}" = "xTRUE" -o "x${_VERBOSE}" = "x1" ]; then
          node index.js --verbose ../repository
        else
          node index.js ../repository
        fi
      env:
        _VERBOSE: ${{ vars.UPDATE_VERBOSE }}
    - name: Commit assets changes
      run: |
        cd repository
        CD=$(pwd)

        git config user.name github-actions
        git config user.email github-actions@github.com

        set +e

        CHANGES=""
        for DIR in `ls`; do
          if [ -d "${CD}/${DIR}" ]; then
            cd "${CD}/${DIR}"
            CHANGED=$(git diff .)
            if [ -n "${CHANGED}" ]; then
              VER=$(awk "/\"${DIR}\": {/,/\"version\": \"*\"/ { if (\$2 != \"{\") print \$2 }" ${CD}/cdn.json | egrep -o "([0-9]{1,}\.)+[0-9]{1,}[A-Za-z0-9\-]{0,}")
              if [ -n "${VER}" ]; then
                MSG="${DIR} (${VER})"
              else
                MSG="${DIR}"
              fi
              echo "> ${MSG}"
              git add .
              if [ -n "${CHANGES}" ]; then
                CHANGES+="
        "
              fi
              CHANGES+="- ${MSG}"
            fi
          fi
        done
        cd ${CD}
        CDN_CHANGED=$(git diff cdn.json)
        if [ -n "${CHANGES}" -o -n "${CDN_CHANGED}" ]; then
          echo "Committing assets changes..."

          if [ -n "${CDN_CHANGED}" ]; then
            git add cdn.json
          fi
          git commit -m "Automatic assets update.

        ${CHANGES}"
          git push
        fi
